"board_length"= 260mm
"board_height"= 200mm
"board_width"= 16.5mm
"token_thickness"= 7mm
"token_diameter"= 32mm
"board_side_lower_height"= 55mm
"board_side_height"= 156.5mm
"board_side_length"= 100mm
"board_slot_width"= "board_length" / 7
"token_ridge"= ( "token_thickness" - 4mm ) / 2
"token_ridge_width"= 1.5mm
"25T_outer_diameter"= 20mm
"25T_inner_diameter"= 9mm
"2T_screw_distance"= 14mm
"2T_outer_thickness"= 2mm
"2T_inner_thickness"= 4.5mm
"MG996R_outer_length"= 54mm
"MG996R_inner_length"= 40mm
"MG996R_width"= 20mm
"MG996R_height"= 26.6mm
"MG996R_full_height"= 45.7mm
"MG996R_full_width"= 55.5mm
"MG996R_screw_distance"= 10mm
"magnet_diameter"= 10mm
"magnet_thickness"= 2mm
"dispenser_barrel_margin"= 2.5mm
"dispenser_wheel_width"= "token_thickness" + 5mm
"dispenser_cover_margin"= 3.0mm
"dispenser_cover_thickness"= 5.0mm
"MG996R_major_axis_distance"= 34.3mm
"MG996R_major_screw_distance"= 48.6mm
"MG996R_minor_screw_distance"= 9.9mm
"MG996R_mid_height"= 37.5mm
"dispenser_slope"= 30deg
"dispenser_cover_length"= 16mm
"dispenser_carrier_width"= 3.5mm
"dispenser_carrier_height"= 50mm
"carrier_width"= "shaft_diameter" * 2
"shaft_diameter"= 8mm
"carrier_thickness"=16mm
"GT2_width"= 7mm
"GT2_outer_diameter"= 18mm
"GT2_inner_diameter"= 12mm
"GT2_pitch_diameter"= 2mm
"GT2_tooth_height"= 1.6mm
"GT2_upper_length"= 0.6mm
"belt_holder_width"= "GT2_width" + 2 * 6mm
"carrier_screw_distance"= "dispenser_cover_thickness" + 3 * 6mm
"magnetometer_offset"= 6mm
"magnetometer_width"= 15mm
"magnetometer_length"= 19mm
"magnetometer_thickness" = 2.5mm
"timing_belt_gap"= 2.5mm
"carrier_height_top"= 6mm + "carrier_thickness" + 0.5mm
"carrier_height_bot"= 6mm + "carrier_thickness" + "GT2_inner_diameter" + 1.0mm + "timing_belt_gap"
"D5@Sketch3"="magnetometer_thickness"
